apiVersion: v1
kind: Config
clusters:
- name: "nadirah-cluster"
  cluster:
    server: "https://rancher.3.252.163.145.sslip.io/k8s/clusters/c-m-xlvss4jl"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      Fk0TnpnegpPRE0wTVRBZUZ3MHlNekEyTWpjd016VTVNREZhRncwek16QTJNalF3TXpVNU1ERmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE5qZzNPRE00TXpReE1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRXlFMVRjSm12a2UvRgo5b29vTTNPWmlVVmVDdUI5V2dkaTVEcnNOZ\
      WV1aWJUbm9vQ2JpeWhxbXh1Mmt2S2JBZjEvcmpUeFFtYlZVc1lHCk5FZVhoRGpnb0tOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGS\
      nhCSmtiaGlOUGFleUJkSFdtam4vRWJ0ekxETUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUYrdApoU\
      XlWNWwyVGtuZVk5QzgxREd0OWlKWVpqaFhtSnVNblg2cjVXZXVNQWlBQ3hGZW1kazRoWjBJN3pzN\
      nlyRzZRCnpwTnR2dDhhcnJJTzJVQjE0OWF0UHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "nadirah-cluster"
  user:
    token: "kubeconfig-user-djqvm5d4ht:fgs9tzkjxvx9mwdgt9sg88kntrlfx547495c857kqpg86nhfkth6mr"


contexts:
- name: "nadirah-cluster"
  context:
    user: "nadirah-cluster"
    cluster: "nadirah-cluster"

current-context: "nadirah-cluster"
