apiVersion: v1
kind: Service
metadata:
  name: cimbcgs-angular-service
  namespace: cimbcgs
spec:
  selector:
    app: cimbcgs-angular
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
